<?php

/**
 * @file
 * Module file for menu_example.
 */

/**
 * @defgroup menu_example Example : Menu
 * @ingroup examples
 * @{
 * Demonstrates uses of the Menu APIs in Drupal.
 *
 * The Page Example module also talks about the menu system, as well
 * as how to use menu arguments to generate pages.
 *
 * @see hook_menu()
 * @see hook_menu_alter()
 * @see hook_menu_link_alter()
 * @see page_example.module
 * @see page_example_menu()
 */

/**
 * Implements hook_menu().
 */
function menu_example_menu() {

  // A simple example which defines a page callback and menu entry.

  // Menu items are defined by placing them in an $items array. The array key
  // (in this case 'menu_example') is the path that defines the menu router
  // entry, so the page will be accessible from the URL
  //  example.com/examples/menu_example.

  $items['examples/menu_example'] = array(

    // We are using the default menu type, so the following can be omitted.
    //   'type' => MENU_NORMAL_ITEM,


    // The menu title. Don NOT use t() which is called by default. You can
    // override the use of t() by defining a 'title callback'. This is explained
    // in the 'menu_example/title_callbacks' example below.
    'title' => 'Menu Example',

    // Description (hover flyover for menu link). Does NOT use t(), which is
    // called automatically.
    'description' => 'Simplest possible menu type, and the parent menu entry for others',

    // Function to be called when this path is accessed.
    'page callback' => '_menu_example_basic_instructions',

    // Arguments to the page callback. Here we'll use them just to provide
    // content for our page.
    'page arguments' => array(t('This page is displayed by the simplest (and base) menu example. Note that the title of the page is the same as the link title. You can also <a href="!link">visit a similar page with no menu link</a>. Also, note that there is a hook_menu_alter() example that has changed the path of one of the menu items.',
            array('!link' => url('examples/menu_example/path_only')))),

    // If the page is meant to be accessible to all users, you can set 'access callback'
    // to TRUE. This bypasses all access checks. For an explanation on
    // how to use the permissions system to restrict access for certain users,
    // see the example 'examples/menu_example/permissioned/controlled' below.
    'access callback' => TRUE,

    // If the page callback is located in another file, spedify it here and
    // that file will be automatically loaded when needed.
    // 'file' => 'menu_example.inc',

    // We can choose which menu gets the link. The default is 'navigation'
    // 'menu_name' => 'navigation',

    // Show the menu link as expanded.
    'expanded' => TRUE,
  );

  return $items;
}  // function menu_example_menu

/**
 * Page callback for the simplest introduction menu entry.
 *
 * @param $content
 *   Some content passed in
 */
function _menu_example_basic_instructions($content = NULL) {
  $base_content = t(
   'This is the base page of the Menu Example. There are a numbe of examples
    here, from the most basic (like this one) to extravagant mappings of loaded
    placeholder arguments. Enjoy!'
  );
  return '<div>' . $base_content . '</div><br /><div>' . $content . '</div>';
}

